# Generated by Django 3.1.2 on 2020-10-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapiQL', '0002_auto_20201021_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Starship',
        ),
    ]
